### ISSUE TITLE
information service caches the contract addresses

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-bridge-monitor#1]
I deployed a new ForeignGivethBridge contract, and updated the config file. However the information service still returns the old addy.

The information service can probably just get the data from the config directly and return it, instead of persisting the config in the db

**Comment by maxkant** [comment]
@perissology 
Added a before hook to the information service to get the addresses from the config instead of persisting it in the db - [commit](https://github.com/Giveth/giveth-bridge-monitor/commit/3863f490e73f76ecc3b87817bcca88c5eeeef3a1)

**Comment by perissology** [comment]
thanks!
