### ISSUE TITLE
Show recipients names directly

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-bridge-monitor#12]
In the table, the monitor currently shows addresses of the recipients. It could simplify your job if you shown the names if available directly.

<img width="1904" alt="screen shot 2019-02-17 at 12 47 42" src="https://user-images.githubusercontent.com/7974813/52918256-3cf88c00-32b2-11e9-82d8-62dd59d170b7.png">

**Comment by bowensanders** [comment]
Solved by PR #17
